Web/NewsRoom.Web/Areas/Administration/Controllers/UsersController.cs
namespace NewsRoom.Web.Areas.Administration.Controllers
{
    using Microsoft.AspNetCore.Mvc;
    using NewsRoom.Services.Data;
    using NewsRoom.Web.ViewModels.Administration.Dashboard.Users;

    public class UsersController : AdministrationController
    {
        private readonly IUsersService usersService;

        public UsersController(IUsersService usersService)
        {
            this.usersService = usersService;
        }

        public IActionResult All()
        {
            var model = this.usersService.All<UserViewModel>();
            return this.View(model);
        }
    }
}

Web/NewsRoom.Web/Controllers/CategoriesController.cs
namespace NewsRoom.Web.Controllers
{
    using System;
    using System.Linq;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Mvc;
    using NewsRoom.Services.Data;
    using NewsRoom.Web.ViewModels.Categories;
    using NewsRoom.Web.ViewModels.NewsViewModels;

    public class CategoriesController : BaseController
    {
        private const int ItemsPerPage = 5;

        private readonly INewsService newsService;
        private readonly ICategoryService categoriesService;

        public CategoriesController(INewsService newsService, ICategoryService categoriesService)
        {
            this.newsService = newsService;
            this.categoriesService = categoriesService;
        }

        public IActionResult Create()
        {
            return this.View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateAsync(CreateCategoryViewModel input)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(input);
            }

            var categoryId = await this.categoriesService.CreateAsync(input.Title, input.Description, input.ImageUrl);
            this.TempData["InfoMessage"] = "Category created!";
            return this.RedirectToAction(nameof(this.ById), new { id = categoryId });
        }

        public IActionResult ById(int id)
        {
            var viewModel = this.categoriesService.GetAll<CategoryViewModel>().FirstOrDefault(x => x.Id == id);
            return this.View(viewModel);
        }

        public IActionResult ByName(string name, int page = 1)
        {
            var viewModel =
               this.categoriesService.GetByName<CategoryViewModel>(name);
            if (viewModel == null)
            {
                return this.NotFound();
            }

            viewModel.NewsPerPage = this.newsService.GetByCategoryId<NewsInCategoryViewModel>(viewModel.Id, ItemsPerPage, (page - 1) * ItemsPerPage);

            var count = this.newsService.GetCountByCategoryId(viewModel.Id);
            viewModel.PagesCount = (int)Math.Ceiling((double)count / ItemsPerPage);
            if (viewModel.PagesCount == 0)
            {
                viewModel.PagesCount = 1;
            }

            viewModel.CurrentPage = page;

            return this.View(viewModel);
        }
    }
}

Web/NewsRoom.Web/Controllers/NewsController.cs
namespace NewsRoom.Web.Controllers
{
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using NewsRoom.Data.Models;
    using NewsRoom.Services.Data;
    using NewsRoom.Web.ViewModels.Administration.Dashboard.NewsViewModel;
    using NewsRoom.Web.ViewModels.NewsVieModels;
    using NewsRoom.Web.ViewModels.NewsViewModels;

    public class NewsController : BaseController
    {
        private readonly INewsService newsService;
        private readonly ICategoryService categoriesService;
        private readonly UserManager<ApplicationUser> userManager;

        public NewsController(
            INewsService newsService,
            ICategoryService categoriesService,
            UserManager<ApplicationUser> userManager)
        {
            this.newsService = newsService;
            this.categoriesService = categoriesService;
            this.userManager = userManager;
        }

        public IActionResult ById(int id)
        {
            var postViewModel = this.newsService.GetById<NewsViewModel>(id);
            if (postViewModel == null)
            {
                return this.NotFound();
            }

            return this.View(postViewModel);
        }

        public IActionResult Create()
        {
            var categories = this.categoriesService.GetAll<CategoryDropDownViewModel>();
            var viewModel = new NewsCreateInputModel
            {
                Categories = categories,
            };
            return this.View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Create(NewsCreateInputModel input)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(input);
            }

            var user = await this.userManager.GetUserAsync(this.User);
            if (!this.ModelState.IsValid)
            {
                return this.View(input);
            }

            var newsId = await this.newsService.CreateAsync(input.Title, input.SecondTitle, input.Content, input.CategoryId, input.ImageUrl, user.Id);
            this.TempData["InfoMessage"] = "News created!";
            return this.RedirectToAction(nameof(this.ById), new { id = newsId });
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var viewModel = this.newsService.GetById<EditNewsViewModel>(id);
            return this.View(viewModel);
        }

        [HttpPost]
        public IActionResult Edit(EditNewsViewModel model)
        {
            var newsId = this.newsService.Update(model.Id, model.Title, model.SecondTitle, model.Content, model.CategoryId, model.ImageUrl, model.Approved);
            return this.RedirectToAction(nameof(this.ById), new { id = newsId });
        }
    }
}

Web/NewsRoom.Web/ViewComponents/NavBarViewComponent.cs
namespace NewsRoom.Web.ViewComponents
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Mvc;
    using NewsRoom.Data.Common.Repositories;
    using NewsRoom.Data.Models;
    using NewsRoom.Services.Mapping;
    using NewsRoom.Web.ViewModels;
    using NewsRoom.Web.ViewModels.Categories;

    public class NavBarViewComponent : ViewComponent
    {
        private readonly IDeletableEntityRepository<Category> categoriesRepository;

        public NavBarViewComponent(IDeletableEntityRepository<Category> categoriesRepository)
        {
            this.categoriesRepository = categoriesRepository;
        }

        public IViewComponentResult Invoke()
        {
            var model = new NavBarModelView
            {
                Categories = this.categoriesRepository.All().To<CategoryViewModel>().ToList(),
            };
            return this.View(model);
        }
    }
}

Web/NewsRoom.Web/Areas/Administration/Views/Shared/_AdminLayout.cshtml
@using NewsRoom.Common
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@this.ViewData["Title"] - @GlobalConstants.SystemName</title>

    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" asp-append-version="true" />
    <link href="~/css/site.min.css" rel="stylesheet" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">@GlobalConstants.SystemName</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <vc:nav-bar></vc:nav-bar>
                </div>
            </div>
        </nav>
    </header>

    <nav class="navbar navbar-expand-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="Administration" asp-controller="Dashboard" asp-action="Index">Dashboard</a>
            <ul class="navbar-nav flex-grow-1">
                <li class="nav-item active">
                    <a class="nav-link" asp-action="Index" asp-controller="Dashboard">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-area="" asp-action="Create" asp-controller="Categories">Add Category</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-area="" asp-action="Create" asp-controller="News">Add News</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-action="All" asp-controller="Users">Add Author</a>
                </li>
            </ul>
        </div>
    </nav>

    <div class="row">
        <div class="container col-8">
            <partial name="_CookieConsentPartial" />
            <main role="main" class="pb-3">
                @this.RenderBody()
            </main>
        </div>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Now.Year - @GlobalConstants.SystemName - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.js" asp-append-version="true"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js" asp-append-version="true"></script>
    <script src="~/lib/moment/min/moment-with-locales.min.js" asp-append-version="true"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @this.RenderSection("Scripts", required: false)
</body>
</html>