Web/NewsRoom.Web/ViewComponents/NavBarViewComponent.cs
namespace NewsRoom.Web.ViewComponents
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Mvc;
    using NewsRoom.Data.Common.Repositories;
    using NewsRoom.Data.Models;
    using NewsRoom.Services.Mapping;
    using NewsRoom.Web.ViewModels;
    using NewsRoom.Web.ViewModels.Categories;

    public class NavBarViewComponent : ViewComponent
    {
        private readonly IDeletableEntityRepository<Category> categoriesRepository;

        public NavBarViewComponent(IDeletableEntityRepository<Category> categoriesRepository)
        {
            this.categoriesRepository = categoriesRepository;
        }

        public IViewComponentResult Invoke()
        {
            var model = new NavBarModelView
            {
                Categories = this.categoriesRepository.All().To<CategoryViewModel>().ToList(),
            };
            return this.View(model);
        }
    }
}

Web/NewsRoom.Web/ViewComponents/SidebarViewComponent.cs
namespace NewsRoom.Web.ViewComponents
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Security.Cryptography.X509Certificates;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Mvc;
    using NewsRoom.Data.Common.Repositories;
    using NewsRoom.Data.Models;
    using NewsRoom.Services.Mapping;
    using NewsRoom.Web.ViewModels;
    using NewsRoom.Web.ViewModels.NewsViewModels;

    public class SidebarViewComponent : ViewComponent
    {
        private readonly IDeletableEntityRepository<News> newsRepository;

        public SidebarViewComponent(IDeletableEntityRepository<News> newsRepository)
        {
            this.newsRepository = newsRepository;
        }

        public IViewComponentResult Invoke()
        {
            var model = new SideBarNewsViewModels
            {
                News = this.newsRepository.All().To<NewsViewModel>().OrderByDescending(x => x.CreatedOn).Take(5).ToList(),
            };
            return this.View(model);
        }
    }
}

Web/NewsRoom.Web/Views/Shared/_Layout.cshtml
@using NewsRoom.Common
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@this.ViewData["Title"] - @GlobalConstants.SystemName</title>

    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" asp-append-version="true" />
    <link href="~/css/site.min.css" rel="stylesheet" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">@GlobalConstants.SystemName</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                        <vc:nav-bar></vc:nav-bar>
                </div>
            </div>
        </nav>
    </header>
    <div class="row">
        <div class="container col-8">
            <partial name="_CookieConsentPartial" />
            <main role="main" class="pb-3">
                @this.RenderBody()
            </main>
        </div>

        <aside class="col-3 magazine-page mt-lg-5 pt-5">
            <vc:sidebar></vc:sidebar>
        </aside>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Now.Year - @GlobalConstants.SystemName - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.js" asp-append-version="true"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js" asp-append-version="true"></script>
    <script src="~/lib/moment/min/moment-with-locales.min.js" asp-append-version="true"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @this.RenderSection("Scripts", required: false)
</body>
</html>